models finished
NewForce-at-Mountwest/bangazon-api-gnocci pull request #1
Opened 2019-05-16 18:57 UTC by Havey3

# Description

Created models for :
Customer
Order
PaymentType
Product
ProductType

## Related Ticket(s)
Ticket 1
Ticket 2
Ticket 3
Ticket 4
Ticket 5

## Steps to Test
Reference Tickets 1-5 (https://trello.com/b/GrGMiBMM/bangazon-api-team-gnocci)
Make sure the models match up with the tickets
Run the code (ctrl + f5) to make sure there are no errors.

# Checklist:
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2019-05-16 19:31 UTC, Tommy-Spurlock commented
👍 Looks good to me.

2019-05-16 19:48 UTC, jordan-castelloe requested changes
Looks super good! Thanks for putting so much thought into this. I left one comment, just @ me again when you've changed it and I'll double check

2019-05-16 19:48 UTC, jordan-castelloe commented on BangazonAPI/BangazonAPI/Models/Order.cs
> +        public List<Customer> CustomerList { get; set; } = new List<Customer>();
We don't need a list of customers because an order can only have one customer. Instead, let's add a property of type Customer 👍

2019-05-17 13:48 UTC, joeywellman commented
👍

2019-05-17 14:03 UTC, jordan-castelloe approved these changes

2019-05-17 14:06 UTC, merged